admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
